services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://218.147.174.79:3307/paddle_dev?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&character_set_server=utf8mb4&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin!@#!@#
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRINGDOC_SWAGGER_UI_ENABLED=true
      - SPRINGDOC_SWAGGER_UI_PATH=/swagger-ui.html
      - LOG_LEVEL_SECURITY=DEBUG
      - LOG_LEVEL_SUPIENCE=DEBUG
      - LOG_LEVEL_WEB=DEBUG
    restart: unless-stopped