spring:
  config:
    import: classpath:oauth.yml
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      timeout: 30m
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
  packages-to-scan: com.supience.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    com.supience: ${LOG_LEVEL_SUPIENCE:DEBUG}
    org.springframework.web: ${LOG_LEVEL_WEB:DEBUG}

file:
  upload-dir: uploads 