spring:
  datasource:
    url: jdbc:mysql://mysql:3306/supience?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8443
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      timeout: 30m
  ssl:
    enabled: true
    key-store: classpath:ssl/supience.p12
    key-store-password: supience123
    key-store-type: PKCS12
    key-alias: supience

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
  packages-to-scan: com.supience.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    org.springframework.security: DEBUG
    com.supience: DEBUG
    org.springframework.web: DEBUG 